#!/usr/bin/env bash
WRK_DIR=$(dirname "$(realpath "$0")")
CUR_DIR=$(pwd)

source ${WRK_DIR}/includes/defaults.sh

# FUNCTIONS
greeting(){
  gum style \
        --foreground 212 --border-foreground 212 --border double \
        --align center --width 70 --margin "1 2" --padding "1 2" \
        'Absolute Awesome Workflow Manager' \
        "McClane Mighty Software - $(date +%Y)" \
        "Apache License 2.0"
  echo
}

list_commands(){
  for f in "${WRK_DIR}/workflows/"*.sh scripts/local/*.sh; do
    [ -f "$f" ] || continue
    basename "$f" .sh
  done
}

choose_command(){
  list_commands | gum filter \
    --limit=1 \
    --header.foreground=15 \
    --height=7 \
    --placeholder="What do you wanna do?"
}

run_command(){
  local command=$1

  log_info "Finding script for command: $command"
  local script="${WRK_DIR}/workflows/${command}.sh"
  [ -x "$script" ] || script="scripts/local/${command}.sh"

  if [ -x "$script" ]; then
    log_info "Triggering command '$command'..."
    WRK_DIR=${WRK_DIR} $script
  else
    log_error "Something is not right! Could not execute the command."
    exit 1
  fi
}

# MAIN
clear

greeting
log_temp "Initializing workflows..." 2
log_info "All good! We are ready to rock."
cat <<EOF | display_markdown
- current workspace: $CUR_DIR
- current branch: $(fetch_current_branch)
EOF
echo

while true; do
  command=$(choose_command)
  if ! run_command $command; then
    sleep 2
    log_temp "It seems like something went wrong..." 2
  fi
  echo
done
