#!/usr/bin/env bash
WRK_DIR=$(dirname "$(realpath "$0")")
CUR_DIR=$(pwd)

source ${WRK_DIR}/includes/defaults.sh

# FUNCTIONS
greeting(){
  gum style \
        --foreground 212 --border-foreground 212 --border double \
        --align center --width 80 --margin "1 2" --padding "1 2" \
        'Absolute Awesome Workflow Manager' \
        "McClane Mighty Software - $(date +%Y)" \
        "Apache License 2.0"
  echo
}

list_local_workflows(){
  if [ -f ${CUR_DIR}/workflows ]; then
    cat ${CUR_DIR}/workflows | sed '/^ *#/d;s/^ *//' | cut -d '=' -f 1
  fi
}

run_local_command(){
  local command_name=$1
  local command_line
 
  if [ -f ${CUR_DIR}/workflows ]; then
    log_debug "Finding '$command_name' in the local workflows..."
    command_line=$(
      cat ${CUR_DIR}/workflows |
        sed "/^$command_name/"'!d;s/^ *//' |
        cut -d '=' -f 2
    )
    if [ ! "$command_line" = "" ]; then
      log_and_run "Running '$command_name'..." \
        $command_line || return 2
    else
        log_debug "Could not find '$command_name' in the workflows. Skipping..."
        return 1
    fi
  else
    log_debug "No workflows detected. Skipping..."
    return 1
  fi
}

list_commands(){
  list_local_workflows
  for f in "${WRK_DIR}/workflows/"*.sh scripts/local/*.sh; do
    [ -f "$f" ] || continue
    basename "$f" .sh
  done
}

choose_command(){
  list_commands | sort | gum filter \
    --limit=1 \
    --strict \
    --header.foreground=15 \
    --height=15 \
    --timeout=1200s \
    --indicator="❯ " \
    --placeholder="What do you wanna do?"
}

run_command(){
  local command=$1

  local local_cmd_status=0
  run_local_command $command || local_cmd_status=$?

  if [ "$local_cmd_status" -eq 2 ]; then
    return 2
  elif [ "$local_cmd_status" -eq 1 ]; then
    log_debug "Finding script for command: $command"
    local script="${WRK_DIR}/workflows/${command}.sh"
    [ -x "$script" ] || script="scripts/local/${command}.sh"

    if [ -x "$script" ]; then
      log_debug "Triggering command '$command'..."
      WRK_DIR="${WRK_DIR}" CUR_DIR="${CUR_DIR}" PWD="${CUR_DIR}" $script
    else
      log_error "Could not execute the command '$command'."
      exit 1
    fi
  fi
}

should_continue_or_start_over() {
  local new="New Worktree"
  local cont="Continue previous work"

  local chosen=$(
    gum choose \
      --padding="1 2" \
      --header="I found unfinished worktrees. What do you wanna do?" \
      "$new" "$cont"
  )

  case "$chosen" in
    "$new") echo start_over ;;
    "$cont") echo continue ;;
  esac
}

choose_a_worktree() {
  case "$(should_continue_or_start_over)" in
    "start_over") git_create_new_worktree ;;
    "continue") git_choose_worktree ;;
  esac
}

# MAIN
[ "$DEBUG" = "true" ] || clear

greeting
#log_temp "Initializing workflows..." 0.7

if ! git_is_repository; then
  log_error "Can't work on non-git folders."
  exit 1
fi

if git_has_uncleaned_worktrees; then
  log_info "The user has unfinished worktrees."
  worktree_path=$(choose_a_worktree)
  cd $worktree_path
else
  log_info "Creating a new worktree..."
  worktree_path=$(git_create_new_worktree)
  cd $worktree_path
fi

log_info "All good! We are ready to rock."
cat <<EOF | display_markdown
- current workspace: $CUR_DIR
- current branch: $(fetch_current_branch)
- current session: ${SESSION}
EOF
echo

while true; do
  command=$(choose_command)
  if [ ! "$command" = "" ]; then
    exit_code=0
    run_command $command || exit_code="$?"

    case "$exit_code" in
      0) continue ;;
      130|200)
        log_info "Bye!"
        exit 0
      ;;
      *)
        log_temp "It seems like something went wrong..." 3
        echo
      ;;
    esac
  fi
done
