#!/usr/bin/env bash

# BOOTSTRAP
WRK_DIR=$(dirname "$(realpath "$0")")
CUR_DIR=$(pwd)

source ${WRK_DIR}/includes/defaults.sh

# FUNCTIONS
greeting(){
  gum style \
        --foreground 212 --border-foreground 212 --border double \
        --align center --width 80 --margin "1 2" --padding "1 2" \
        'Absolute Awesome Workflow Manager' \
        "McClane Mighty Software - $(date +%Y)" \
        "Apache License 2.0"
  echo
}

choose_command(){
  local workflows
  workflows=$(list_all_workflows) || return 1

  echo "$workflows" | sort | gum filter \
    --limit=1 \
    --strict \
    --header.foreground=15 \
    --height=15 \
    --timeout=1200s \
    --indicator="❯ " \
    --placeholder="What do you wanna do?"
}

list_all_workflows(){
  workflow_list_local &&
    workflow_list_enabled
}

run_command(){
  local command=$1

  local local_cmd_status=0
  workflow_run_local $command || local_cmd_status=$?

  if [ "$local_cmd_status" -eq 2 ]; then
    return 2
  elif [ "$local_cmd_status" -eq 1 ]; then
    workflow_run_enabled $command
  fi
}

should_continue_or_start_over() {
  local new="New Worktree"
  local cont="Continue previous work"
  local chosen

  chosen=$(
    gum choose \
      --padding="1 2" \
      --header="I found unfinished worktrees. What do you wanna do?" \
      "$cont" "$new"
  ) || return 1

  case "$chosen" in
    "$new") echo start_over ;;
    "$cont") echo continue ;;
  esac
}

choose_a_worktree() {
  local choice
  choice=$(should_continue_or_start_over) || return 1

  case "$choice" in
    "start_over")
      log_info "Creating a new worktree..."
      git_create_new_worktree
    ;;
    "continue")
      log_info "Resuming last session..."
      git_choose_worktree
    ;;
  esac
}

# MAIN
[ "$DEBUG" = "true" ] || clear

greeting
#log_temp "Initializing workflows..." 0.7

if ! git_is_repository; then
  log_error "Can't work on non-git folders."
  exit 1
else
  log_debug "Is a valid Git repository"
fi

if ! workflow_has_any_enabled; then
  log_error "No workflow is enabled. Did you run '${WRK_DIR}/wkf_init.sh'?"
  exit 4
else
  log_debug "It has workflows enabled."
fi

if git_has_uncleaned_worktrees; then
  log_info "The user has unfinished worktrees."
  worktree_path=$(choose_a_worktree)
  cd $worktree_path
else
  log_info "Creating a new worktree..."
  worktree_path=$(git_create_new_worktree)
  cd $worktree_path
fi

log_info "All good! We are ready to rock."
cat <<EOF | display_markdown
- workspace: ${CUR_DIR}
- branch: $(fetch_current_branch)
- worktree: ${worktree_path}
EOF

if [ "$DEBUG" = "true" ]; then
cat <<EOF | display_markdown
- CONFIG_DIR: ${CONFIG_DIR}
- WORKFLOW_DIR: ${WORKFLOW_DIR}
- LOCAL_WORKFLOW_DIR: ${LOCAL_WORKFLOW_DIR}
EOF
fi

while true; do
  echo
  command=$(choose_command) || exit 4

  if [ ! "$command" = "" ]; then
    exit_code=0
    run_command $command || exit_code="$?"

    case "$exit_code" in
      0) continue ;;
      "130"|"200")
        log_info "Bye!"
        exit 0
      ;;
      *)
        log_temp "Command existed with $exit_code." 3
      ;;
    esac
  fi
done
